services:
  postgres:
    image: postgres:15
    container_name: booking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: booking-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:4.2.0
    container_name: booking-kafka
    ports:
      - "9092:9092"

  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    depends_on:
      - postgres
    ports:
      - "8001:8001"

  booking-service:
    build: ./services/booking-service
    container_name: booking-service
    depends_on:
      - postgres
      - inventory-service
    ports:
      - "8000:8000"
      
volumes:
  postgres_data: